version: "3"

services:
  mongo:
    image: mongo:latest
    container_name: note-taking-app-mongodb-container
    restart: unless-stopped
    volumes:
      - database-data:/data/db
    networks:
      - bridge-network

  note-taking-app:
    build:
      context: .
      dockerfile: Dockerfile
    image: note-taking-app
    container_name: note-taking-app-container
    restart: unless-stopped
    env_file: .env
    depends_on:
      - mongo
    environment:
      - MONGO_URL=mongodb://mongo:27017/note-taking-app
    networks:
      - bridge-network
    command: yarn start

  nginx-webserver:
    image: nginx:mainline-alpine
    container_name: note-taking-app-nginx-container
    restart: unless-stopped
    ports:
      - 80:80
    volumes:
      - static-files:/var/www/static
      - ./nginx-conf:/etc/nginx/conf.d
    depends_on:
      - note-taking-app
    networks:
      - bridge-network

networks:
  bridge-network:
    driver: bridge

volumes:
  database-data:  
  static-files:
    driver: local
    driver_opts:
      type: none
      device: ./public/
      o: bind
